events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://api:5000/;
        }

        location /status/ {
            proxy_pass http://status-service:5000/;
        }

    }
}
